name: Linux_CI
on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-python@v3
         with:
           python-version: '3.x'
           architecture: 'x64'
       - name: 'Setup TVM EP requirements'
         run: |
           set -e -x 
           sudo apt-get update
           sudo apt-get install -y libtinfo-dev zlib1g-dev build-essential libedit-dev libxml2-dev
           python3 -m pip install -r ${{ github.GITHUB_WORKSPACE }}/tools/ci_build/github/linux/tvm/requirements.txt
       - name: 'Build and Test'
         run: |
           python3 ${{ github.GITHUB_WORKSPACE }}/tools/ci_build/build.py --build_dir build --config Release --skip_submodule_sync --parallel --enable_pybind --disable_contrib_ops --disable_ml_ops --skip_onnx_tests --use_tvm --ctest_path ""
